SAVE SCREEN TO PANTA6
DO WHILE .T.
SET COLOR TO W/N
@ 6,43 CLEAR TO 10,63
SET COLOR TO W+/B,GR+/R
@ 5,42 CLEAR TO 9,62
@ 5,42 TO 9,62 
@ 22,5 CLEAR TO 24,74
@ 22,5 TO 24,74
@ 6,44 PROMPT 'POR NOMBRE' MESSAGE 'BUSCA UNA PERSONA POR SU NOMBRE '
@ 7,42 SAY '쳐컴컴컴컴컴컴컴컴컴�'
@ 8,44 PROMPT 'POR DATOS' MESSAGE 'BUSCA UNA PERSONA MEDIANTE UN DATO PROPORCIONADO.'
MENU TO OPC
IF LASTKEY()=27
*     SET COLOR TO N/W
*     @ 5,42 CLEAR TO 9,62
     SET COLOR TO W+/B,GR+/R
     EXIT
ENDIF
    DO CASE
        CASE OPC=1
            DO NOMPER
        CASE OPC=2
            DO PAISPER
    ENDCASE
ENDDO

RESTORE SCREEN FROM PANTA6
