SAVE SCREEN TO CEELA1
SET WRAP ON

DO WHILE .T.
   SET COLOR TO W/N
   @ 6,28 CLEAR TO 10,41
   SET COLOR TO W+/B,GR+/R
   @ 5,27 CLEAR TO 9,40
   @ 5,27 TO 9,40 
   @ 22,5 CLEAR TO 24,74
   @ 22,5 TO 24,74
   @ 6,29 PROMPT 'POR PERSONA' MESSAGE 'INDICA TODAS LAS OPERACIONES REALIZADAS POR LA PERSONA BUSCADA'
   @ 7,27 SAY 'ÃÄÄÄÄÄÄÄÄÄÄÄÄ´'
   @ 8,29 PROMPT 'POR CANJE' MESSAGE 'INDICA TODAS LAS OPERACIONES REALIZADAS SEGéN EL TOPICO SELECCIONADO' 
   MENU TO OPC
   IF LASTKEY()=27
         EXIT
   ENDIF
      DO CASE 
         CASE OPC = 1
            DO BUSPER
         CASE OPC = 2
            DO BUSCAN   
     ENDCASE
     ENDDO
     RESTORE SCREEN FROM CEELA1
