SET DATE FRENCH
X=2
TITUL='                                                                      '
DO WHILE .T.
DO MESA
SET COLOR TO W+/B,GR+/R
@ 2,1 CLEAR TO 22,78
@ 2,1 TO 22,78
NOM=SPACE(40)
DIREC=SPACE(150)
*DIREC2=SPACE(70)
PAI=SPACE(20)
CARG=SPACE(60)
COD=0
USE IDENTIFI INDEX IDENT
REINDEX
GO BOTTOM
STORE CODIGO TO ULTCOD
@ 3,5 SAY 'INCLUIR DATOS DEL CANJE O DIRECCIONES'
DIR = 'N'
@ 2,63 SAY 'CODIGO'
@ 2,70 GET COD PICT '999'
READ
  IF LASTKEY()=27
       EXIT
  ENDIF
SEEK COD
   IF FOUND()
       NOM=NOMBRE
       DIREC=DIRECCION
       *DIREC2=DIRECCION2
       CARG=CARGO
       PAI=PAIS
    ENDIF
SET COLOR TO GR+/R
@ 24,0 CLEAR TO 24,79
@ 24,5 SAY '<F3>MODIFICAR    <F4>IMPRIMIR TALON'
SET COLOR TO W+/B,GR+/R
SET KEY -2 TO MODIFI
SET KEY -3 TO TALON
@ 6,3 SAY 'NOMBRE:'
@ 6,10 GET NOM PICTURE '@!'
@ 6,51 SAY 'PAIS:'
@ 6,56 GET PAI PICTURE '@!'
@ 8,3 SAY 'CARGO:'
@ 8,9 GET CARG PICTURE '@!'
@ 10,3 SAY 'DIRECCION:'
@ 10,13 GET DIREC PICTURE '@!'
*@ 11,3 GET DIREC2 PICT '@!'
READ
   IF COD=0 .AND. NOM <>' '
        APPEND BLANK
        COD=ULTCOD+1
        REPLACE CODIGO WITH COD
        REPLACE NOMBRE WITH NOM
        REPLACE CARGO WITH CARG
        REPLACE PAIS WITH PAI
        REPLACE DIRECCION WITH DIREC
        * REPLACE DIRECCION2 WITH DIREC2
    ENDIF
@ 2,70 SAY CODIGO
STORE CODIGO TO CODI
@ 24,0 CLEAR TO 24,79
SET KEY -2 TO
SET KEY -3 TO
USE
RESP='N'
@ 12,20 SAY 'DESEA INTRODUCIR DATOS DE CANJE? S/N'
@ 12,58 GET RESP PICTURE '@!'
READ
IF RESP = 'S'
   @ 12,20 CLEAR TO 12,60
   USE DATOS INDEX DAT 
REINDEX
   GO BOTTOM
   NUMERO=NUM+1
   APPEND BLANK
   REPLACE NUM WITH NUMERO
   REPLACE CODIGO WITH CODI
   REPLACE FECHA WITH DATE()
   @ 24,70 SAY CODIGO
   @ 12,3 SAY 'FECHA CANJE:'
   @ 12,15 GET FECHA 
   READ
   @ 12,24 SAY 'TIPO OPERACION (DONACION/CANJE):'
   @ 12,40 PROMPT 'DONACION'
   @ 12,49 PROMPT 'CANJE'
   MENU TO TIP
      DO CASE
         CASE TIP=1
              REPLACE TIPO_OP WITH 'DONACION'
         CASE TIP=2
              REPLACE TIPO_OP WITH 'CANJE'
      ENDCASE
   NUMERO='S/N            '
   @ 14,3 SAY 'NUMERO COMUNICADO:'
   @ 14,21 GET NUMERO PICT '@!' 
   READ
   REPLACE N_COMUNICA WITH NUMERO
   @ 14,37 SAY 'OPERACION: (RECIBO/ENVIO)'
   @ 14,49 PROMPT 'RECIBO' 
   @ 14,56 PROMPT 'ENVIO'
   MENU TO OP
      DO CASE
         CASE OP=1
             REPLACE OPERACION WITH 'RECIBO'
         CASE OP=2
             REPLACE OPERACION WITH 'ENVIO'
      ENDCASE
   @ 16,3 SAY 'TIPO: (REVISTA/LIBRO/TRABAJO)'
   @ 16,10 PROMPT 'REVISTA'
   @ 16,18 PROMPT 'LIBRO'
   @ 16,24 PROMPT 'TRABAJO'
   MENU TO LIB
       DO CASE
          CASE LIB=1
             REPLACE TIPO WITH 'REVISTA'
          CASE LIB=2
             REPLACE TIPO WITH 'LIBRO'
          CASE LIB=3
             REPLACE TIPO WITH 'TRABAJO'
       ENDCASE
   @ 16,40 SAY 'CUANTAS UNIDADES:'
   UNI=1
   @ 16,57 GET UNI PICT '99'
   READ
   REPLACE CANTIDAD WITH UNI
   @ 18,32 SAY 'TITULO:'
   @ 19,3 GET TITUL PICTURE '@!'
   READ
   REPLACE TITULO WITH TITUL
ENDIF
RESP='N'
@ 20,20 SAY 'DESEA INTRODUCIR OTRO DATO? S/N' 
@ 20,52 GET RESP
READ
IF RESP='N'
   EXIT
ENDIF
ENDDO




PROCEDURE MODIFI
        REPLACE CODIGO WITH COD
        REPLACE NOMBRE WITH NOM
        REPLACE CARGO WITH CARG
        REPLACE PAIS WITH PAI
        REPLACE DIRECCION WITH DIREC
        *REPLACE DIRECCION2 WITH DIREC2
 SET KEY -2 TO
 SET COLOR TO GR+/R
 @ 24,0 CLEAR TO 24,79 
 @ 24,5 SAY 'MODIFICACION REALIZADA......PULSE <ENTER>'
 @ 23,1 SAY ''
 WAIT''
 @ 24,0 CLEAR TO 24,79
 SET COLOR TO W+/B,GR+/R
 RETURN


PROCEDURE DIRECC
SAVE SCREEN TO PANTA7
COLORES=SETCOLOR()
USE IDENTIFI INDEX IDENT
REINDEX
SET COLOR TO W/N
@ 6,11 CLEAR TO 22,71
SET COLOR TO N/W,GR+/R
GO TOP
@ 5,10 CLEAR TO 21,70
@ 5,10 TO 21,70 DOUBLE
DBEDIT (6,11,20,69)
IF LASTKEY()=27
     COD=0
ELSE
     COD=CODIGO
     NOM=NOMBRE
ENDIF
SET COLOR TO &COLORES
RESTORE SCREEN FROM PANTA7
RETURN



PROCEDURE CANJES
COD=CODIGO
CODIG=CODIGO
SAVE SCREEN TO PANTA7
COLORES=SETCOLOR()
USE DATOS INDEX DAT
REINDEX
SEEK COD
SET COLOR TO W/N
@ 6,2 CLEAR TO 22,79
SET COLOR TO N/W,GR+/R
@ 5,1 CLEAR TO 21,78
@ 5,1 TO 21,78 DOUBLE
DBEDIT (6,2,20,77)
IF LASTKEY()=27
     COD=CODIG
ENDIF
SET COLOR TO &COLORES
RESTORE SCREEN FROM PANTA7
USE IDENTIFI INDEX IDENT
SEEK CODIG

RETURN

PROCEDURE TALON
DO WHILE .T.
    IF .NOT. ISPRINTER()
       EXIT
    ENDIF
    SET DEVICE TO PRINT
    @ X,10 SAY NOMBRE
    @ X,53 SAY PAIS
    @ X+1,10 SAY CARGO
    @ X+2,10 SAY DIRECCION
    @ X+3,10 SAY DIRECCION2
    X=X+5

    EXIT
ENDDO
SET DEVICE TO SCREEN
RETURN
