CD\PROGRAMA\CLIPPER
CLIPPER \PROGRAMA\CANJES\CANJE -o\PROGRAMA\CANJES
rem BLINKER FI \PROGRAMA\CANJES\CANJE LI CLIPPER,EXTEND
plink86 FI \PROGRAMA\CANJES\CANJE LIB CLIPPER,extend
CD\PROGRAMA\CANJES
rem CANJE
rem cls