SAVE SCREEN TO TOTALES1

SET COLOR TO N/W
@ 1,1 CLEAR TO 23,78
@ 1,1 TO 23,78
@ 2,20 SAY 'ESTADISTICAS DE DATOS DE CANJES'
@ 3,2 TO 22,35
SET COLOR TO R+/W
@ 4,3 SAY 'PERSONAS E INSTITUCIONES'
@ 4,43 SAY 'LIBROS, REVISTAS, TRABAJOS'
SET COLOR TO N/W
@ 6,3 SAY 'TOTAL DE INSCRITOS:'
USE IDENTIFI INDEX IDENT
REINDEX
X=0
Y=0
Z=0
K=0
W=0
GO TOP
DO WHILE.T.
        IF EOF()
             EXIT
        ENDIF
        IF PAIS='VENEZUELA'
            Y=Y+1
        ENDIF
        IF PAIS='MEXICO'.OR.PAIS='COLOMBIA'.OR.PAIS='CHILE'.OR.PAIS='ARGENTINA'.OR.PAIS='GUATEMALA'.OR.PAIS='CUBA'.OR. PAIS='HAITI'.OR.PAIS='R.DOMINICANA'.OR.PAIS='HONDURAS'.OR.PAIS='NICARAGUA'.OR.PAIS='COSTA RICA'.OR.PAIS='SALVADOR'
            Z=Z+1
        ELSE
            IF PAIS='PANAMA'.OR.PAIS='BRASIL'.OR.PAIS='BOLIVIA'.OR.PAIS='PERU'.OR.PAIS='ECUADOR'.OR.PAIS='PARAGUAY'.OR.PAIS='URUGUAY'   
                Z=Z+1
            ELSE
                IF PAIS='ESTADOS UNIDOS'.OR.PAIS='CANADA'.OR.PAIS='ALASKA'
                    W=W+1
                ELSE
                   IF PAIS<>'VENEZUELA'
                       K=K+1
                   ENDIF
                ENDIF
            ENDIF
        ENDIF
        X=X+1
        SKIP
ENDDO
@ 6,30 SAY X PICTURE '9999'
@ 8,3 SAY 'TOTALES EN VENEZUELA:'
@ 8,31 SAY Y PICTURE '999'
@ 10,3 SAY 'TOTALES EN AMERICA LATINA'
@ 10,31 SAY Z PICTURE '999'
@ 12,3 SAY 'TOTALES EN NORTEAMERICA:'
@ 12,31 SAY W PICTURE '999'
@ 14,3 SAY 'TOTALES EN EUROPA'
@ 14,31 SAY K PICTURE '999'
USE DATOS INDEX DAT
@ 3,40 TO 22,77
@ 6,42 SAY 'TOTAL RECIBIDO:'
GO TOP
X=0
Y=0
DO WHILE .T.
        IF EOF()
                EXIT
        ENDIF
        IF OPERACION='RECIBO'
             X=X+1
        ENDIF
        IF OPERACION='ENVIO'
                Y=Y+1
        ENDIF
        SKIP
ENDDO
@ 6,72 SAY X PICTURE '9999'
@ 8,42 SAY 'TOTAL ENVIOS:'
@ 8,72 SAY Y PICTURE '9999'

WAIT''
RESTORE SCREEN FROM TOTALES1
