SET WRAP ON
SET TALK OFF
DO WHILE .T.
DO FONDO
STORE 1 TO SEMAFORO
STORE 1 TO AYU
@ 8,57 CLEAR TO 12,61
@ 8,57 TO 12,61 DOUBLE
DO TIEMPO3
@ 7,54 CLEAR TO 13,64
@ 7,54 TO 13,64 DOUBLE
DO TIEMPO3
@ 6,51 CLEAR TO 15,67
@ 6,51 TO 15,67 DOUBLE
DO TIEMPO3
@ 5,48 CLEAR TO 16,70
@ 5,48 TO 16,70 DOUBLE
DO TIEMPO3
@ 4,45 CLEAR TO 17,73
@ 4,45 TO 17,73 DOUBLE
DO TIEMPO3
@ 3,42 CLEAR TO 18,76
@ 3,42 TO 18,76 DOUBLE
DO TIEMPO3
@ 4,43 SAY "컴컴컴횭USQUEDA DE LIBROS컴컴컴컴"
@ 6,44 PROMPT " >    BUSQUEDA POR TITULO    <" MESSAGE 'SE BUSCAN MEDIANTE UNA PALABRA EN EL TITULO'
@ 8,44 PROMPT " >    BUSQUEDA POR CODIGO    <" MESSAGE 'MEDIANTE EL CODIGO, PROPORCIONAMOS LOS DATOS DEL LIBRO'
@ 10,44 PROMPT " >    LISTADO POR AUTOR      <" MESSAGE 'SE PROPORCIONA UNA LISTA DE LIBROS DE UN AUTOR'
@ 12,44 PROMPT " >   LISTADO POR MATERIA     <" MESSAGE 'SE MUESTRA UNA LISTA DE LIBROS SEGUN LA MATERIA DADA'
@ 14,44 PROMPT " >LISTADO DE LIBROS FALTANTES<" MESSAGE 'LISTADO DE LIBROS QUE FALTAN EN LA BIBLIOTECA'
@ 16,44 PROMPT " >         SALIR             <" MESSAGE 'REGRESAMOS AL PRIMER MENU'
MENU TO OP
    DO CASE
        CASE OP = 1
             DO TITULO
        CASE OP = 2
             DO BUSCOD
        CASE OP = 3
           DO BUSAUTOR
        CASE OP = 4
            DO LISTMATE
        CASE OP = 5
             DO LISTFALT
        CASE OP = 6
              EXIT
    ENDCASE
ENDDO


PROCEDURE MENSAJE
     SET COLOR TO N/W
     @ 12,16 TO 14,58 DOUBLE
     @ 13,17 SAY "EL LIBRO NO SE ENCUENTRA, PRUEBE DE NUEVO"
     SET COLOR TO
RETURN