CD\PROGRAMA\CLIPPER
CLIPPER \PROGRAMA\bibliote\CONTROL -o\PROGRAMA\bibliote
plink86 FI \PROGRAMA\bibliote\CONTROL LIB CLIPPER,extend
rem BLINKER FI \PROGRAMA\bibliote\CONTROL LI CLIPPER,extend
CD\PROGRAMA\bibliote
